### ISSUE TITLE
CPT, Taxonomias e meta-campos

### ISSUE THREAD

**Issue by jnz93** [jnz93/a2-management#5]
## Custom post Type

Após a conclusão da edição do perfil de acompanhante uma função disparada será encarregada de criar um "post" que será o perfil da(o) modelo carregando todos os dados preenchidos e salvando em meta-campos e taxonomias. 
Esse "post" será um Custom post type chamado `a2_escort`, a url deve ser amigável, algo como `/acompanhante/nome-da-acompanhante`.
O CPT `a2_escort`também receberá algumas taxonomias e tags para salvar determinados tipos de dados, coisas como `gênero, cor do cabelo, serviços oferecidos, país, estado, cidade, etc...`

Essa será a estratégia para que possamos utilizar todos esses dados nas buscas front-end.

### Observações
- **Dessa forma todos os dados salvos no perfil do usuário serão utilizados para preencher os campos da página de perfil.**
- **Páginas de perfil não ficaram disponíveis para edição diretamente. Lembre-se, elas refletem os dados salvos no perfil do usuário**

## Tarefas 
- [x] Criar CPT `a2_escort` que receberá os perfis de acompanhantes.
  - [x] Criar taxonomias
    - [x] Adicionar valores padrões as taxonomias

- [x] Edição do perfil
  - [x] Listar as opções de configuração de perfil conforme as taxonomia referente na edição do perfil.
  - [x] Input select com múltiplos itens salvam apenas um valor no meta-campo
      > Uma possibilidade é alterar o select para [input chips](https://materializecss.com/chips.html). Ou talvez identificar uma forma de pegar todos os valores selecionados no select
