### ISSUE TITLE
Fixes: Meta campos e Taxonomias

### ISSUE THREAD

**Issue by jnz93** [jnz93/a2-management#9]
# Renomeações

- [x] Taxonomias
  - Gênero `profile_genre`
  - Etnia `profile_ethnicity`
  - Signo `profile_sign`
  - Locais `profile_place_of_service`
  - Especialidades `profile_specialties`
  - Serviços `profile_services`
  - Localização	`profile_localization`
  - Idiomas `profile_languages`
  - Dias de trab. `profile_work_days`
  - Formas de pag.  `profile_payment_methods`
  - Preferência	`profile_preference`

- [x] Meta Campos

  **Mídias**
  - Foto de perfil `Foto destacada de post`
  - Foto de capa `_profile_cover`
  - Galeria de fotos `_profile_gallery`
  - Galeria de vídeos `_profile_videos`
  
  **Detalhes pessoais**
  - Altura `_profile_height`
  - Peso `_profile_weight`
  - Cor dos olhos `_profile_eye_color`
  - Cor do cabelo `_profile_hair_color`
  - Tamanho dos seios `_profile_tits_size`
  - Busto `_profile_bust_size`
  - Cintura `_profile_waist_size`
  
  **Dados Pessoais**
  - Telefone/Whatsapp `_profile_whatsapp`
  - Idade (Data de nascimento) `_profile_age`
  - Endereço `_profile_address`
  - CEP `_profile_cep`
  - Horário de expediente `_profile_office_hour`
  
  **Redes sociais**
  - Instagram `_profile_instagram`
  - TikTok `_profile_tiktok`
  - OnlyFans `_profile_onlyfans`
  
  **Valores**
  - Cachê rapidinha `_profile_cache_quickie`
  - Cachê 30 minutos `_profile_cache_half_an_hour`
  - Cache 1hora `_profile_cache_hour`
  - Cachê pernoite `_profile_cache_overnight_stay`
  - Cachê promoção `_profile_cache_promotion`
  - Cache promoção ativado/ `_profile_cache_promotion_activated`
  
  **Segurança**
  - Perfil verificado `_profile_verified`
  - Verificação de documentos `_profile_verified_documents`
  
  **Comercial**
  - Nível de perfil `_profile_level`
  - Pacote de vantagens  `_profile_advantage_package`
  - Validade da assinatura `_profile_expires_package`
  - Perfil ativado/desativado `_profile_is_active`

## Fixes
> Como alteramos os nomes e adicionamos novas taxonomias e post-metas vamos precisar revisar o que  e como está sendo salvo. 
- [x] Revisar salvamento de post meta campos
- [x] Revisar salvamento de taxonomias
- [x] Fix setar taxonomia métodos de pagamento no perfil
